title: Jacob Olson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About
  <br>Student of algorithm design, philosophy, and ethics.
  If you see me without headphones or a hoodie, then it's an impostor.<br><br>
  
  Contact(s) and Credential(s)
  <br>
  <a href = "mailto: jacob3.olson@umontana.edu">Student Email</a><br>
  <a href="./images/Resume.pdf" download="JacobOlson">Resume</a><br>
  <a href="./images/TestOutCertificate.pdf" download="TestOutCertification">TestOut Certificate</a><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
